### PR TITLE
Add job func

### PR DESCRIPTION
**Pull request by wsdjeg**
@prabirshrestha
   I just write a script for vim and neovim job feature, I have read you plugin, but as I know there is no func named `job_send()` in vim.

https://github.com/prabirshrestha/async.vim

### CODE REVIEW

**Comment by prabirshrestha** [comment]
It used to work in the vim patch I had. Seems like the api has changed since. I couldn't find `job_send` in vim. Most likely got replaced with `ch_sendraw` and `ch_readraw`.

Here is an example. That uses it.

https://github.com/vim/vim/blob/7ef3810d28b7ab2edbfcafab3fe8ad8bc2c2f138/src/testdir/test_channel.vim#L482-L509

**Comment by wsdjeg** [comment]
@prabirshrestha got it, thanks a lot!

**Comment by prabirshrestha** [comment]
@wsdjeg fixed while refactoring. Tested it on both vim and neovim. https://github.com/prabirshrestha/async.vim/pull/3
Although I temporarily removed `system` fallback

**Comment by wsdjeg** [comment]
@prabirshrestha  nice work, will have a look.

**Comment by wsdjeg** [comment]
@prabirshrestha  nice work, will have a look.

**Pull request merged**
