### PR TITLE
Update general.vim. fix typos

### PR DESCRIPTION
**Pull request by horryq**
fix typos (filnxtToOF to filnxtToO)

### CODE REVIEW

**Comment by wsdjeg** [comment]
`F` is new feature of neovim.it will not echo filename and lines info when you firsttime open a file

**Comment by wsdjeg** [comment]
This feature is merged in Vim 7.4.1570 

see
https://github.com/neovim/neovim/pull/4446

**Comment by horryq** [comment]
ok, thank you.

**Comment by wsdjeg** [comment]
I have add some checking for the options,now it should works better.

**Pull request closed without merging**
